services:
  tempus:
    image: crypto-chemistry-lab
    working_dir: /home/usero
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - target: 4444
        published: 4444
        protocol: tcp