version: "3.8"

services:
  aesaas:
    image: crypto-aesaas:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - target: 18271
        published: 18271
        protocol: tcp