services:
  cjne:
    image: rev-cjne:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: any
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    read_only: true
    volumes:
      - ../src/flag.txt:/flag.txt:ro
    environment:
      - NODE_ENV=production