version: '3.8'
services:
  cyberjawara:
    container_name: babybrowser
    restart: always
    build:
      context: .
    working_dir: /home/pwn
    ports:
      - "10014:8080" # exposed:local
    read_only: false